spring.application.name=inventory_system

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/inventory_system?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.sql.init.mode=always
spring.sql.init.continue-on-error=true

spring.thymeleaf.cache=false

server.port=${PORT:8080}

ims.auth.username=admin
ims.auth.password=admin123
